language: cpp
compiler: clang
dist: trusty

os:
  - osx

before_script:

  - brew install ace
  - brew install mysql
  - brew install openssl readline ace coreutils bash bash-completion md5sha1sum

  - mkdir build
  - cd build
  - cmake -DTOOLS=0 -DSCRIPTS=1 -DREADLINE_INCLUDE_DIR=/usr/local/opt/readline/include -DREADLINE_LIBRARY=/usr/local/opt/readline/lib/libreadline.dylib -DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include -DOPENSSL_SSL_LIBRARIES=/usr/local/opt/openssl/lib/libssl.dylib -DOPENSSL_CRYPTO_LIBRARIES=/usr/local/opt/openssl/lib/libcrypto.dylib ..

script: make -j4
